import { hashPassword } from "../../utils/password";

export const seedData = {
  organizations: [
    {
      id: "cln_main_001",
      legalName: "Organizationa Exemplo LTDA",
      tradeName: "Organizationa Exemplo",
      bookingPageSlug: "organizationa-exemplo",
      timezone: "America/Sao_Paulo",
      publicDescription: "Clínica multidisciplinar com agenda online para consultas, estética e terapias.",
      publicPhone: "+5511911111111",
      publicEmail: "contato@organization.test",
      addressLine: "Avenida Paulista",
      addressNumber: "1000",
      district: "Bela Vista",
      city: "São Paulo",
      state: "SP",
      postalCode: "01310-100",
      coverImageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1400&q=80",
      logoImageUrl: null,
      galleryImageUrls: [],
      isStorefrontPublished: true,
    },
    {
      id: "cln_dental_001",
      legalName: "Odonto Centro LTDA",
      tradeName: "Odonto Centro",
      bookingPageSlug: "odonto-centro",
      timezone: "America/Sao_Paulo",
      publicDescription: "Atendimento odontológico com horários para avaliação, limpeza e acompanhamento.",
      publicPhone: "+5511944444444",
      publicEmail: "contato@odonto.test",
      addressLine: "Rua das Flores",
      addressNumber: "250",
      district: "Centro",
      city: "São Paulo",
      state: "SP",
      postalCode: "01010-000",
      coverImageUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1400&q=80",
      logoImageUrl: null,
      galleryImageUrls: [],
      isStorefrontPublished: true,
    },
  ],
  users: [
    {
      id: "usr_admin_001",
      organizationId: "cln_main_001",
      fullName: "Ana Martins",
      email: "admin@organization.test",
      phone: "+5511911111111",
      role: "administrator",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_reception_001",
      organizationId: "cln_main_001",
      fullName: "Bruna Lopes",
      email: "recepcao@organization.test",
      phone: "+5511922222222",
      role: "reception",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_pro_001",
      organizationId: "cln_main_001",
      fullName: "Dr. Ricardo Alves",
      email: "ricardo@organization.test",
      phone: "+5511933333333",
      role: "provider",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_admin_002",
      organizationId: "cln_dental_001",
      fullName: "Mariana Costa",
      email: "admin@odonto.test",
      phone: "+5511944444444",
      role: "administrator",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
  ],
  providers: [
    {
      id: "pro_001",
      organizationId: "cln_main_001",
      fullName: "Dra. Ana Souza",
      specialty: "Organizationa Geral",
      isActive: true,
    },
    {
      id: "pro_002",
      organizationId: "cln_main_001",
      fullName: "Dr. Ricardo Alves",
      specialty: "Cardiologia",
      isActive: true,
    },
    {
      id: "pro_003",
      organizationId: "cln_dental_001",
      fullName: "Dra. Paula Nunes",
      specialty: "Odontologia",
      isActive: true,
    },
  ],
  providerAvailabilities: [
    {
      id: "avl_001",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      weekday: 1,
      workStart: "08:00",
      workEnd: "18:00",
      lunchStart: "12:30",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_002",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      weekday: 2,
      workStart: "08:00",
      workEnd: "18:00",
      lunchStart: "12:30",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_003",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      weekday: 3,
      workStart: "08:00",
      workEnd: "18:00",
      lunchStart: "12:30",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_004",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      weekday: 1,
      workStart: "09:00",
      workEnd: "17:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_005",
      organizationId: "cln_dental_001",
      providerId: "pro_003",
      weekday: 1,
      workStart: "08:00",
      workEnd: "16:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
  ],
  customers: [
    {
      id: "pat_001",
      organizationId: "cln_main_001",
      fullName: "Carlos Pereira",
      email: "carlos@customer.test",
      phone: "+5511999999999",
    },
    {
      id: "pat_002",
      organizationId: "cln_main_001",
      fullName: "Fernanda Lima",
      email: "fernanda@customer.test",
      phone: "+5511988888888",
    },
    {
      id: "pat_003",
      organizationId: "cln_main_001",
      fullName: "Julio Rocha",
      email: null,
      phone: "+5511977777777",
    },
    {
      id: "pat_004",
      organizationId: "cln_dental_001",
      fullName: "Patricia Gomes",
      email: "patricia@customer.test",
      phone: "+5511966666666",
    },
  ],
  bookings: [
    {
      id: "apt_001",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      customerId: "pat_001",
      createdByUserId: "usr_reception_001",
      status: "scheduled",
      startsAt: new Date("2026-04-20T09:00:00-03:00"),
      endsAt: new Date("2026-04-20T09:30:00-03:00"),
      notes: "Retorno",
    },
    {
      id: "apt_002",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      customerId: "pat_002",
      createdByUserId: "usr_reception_001",
      status: "confirmed",
      startsAt: new Date("2026-04-20T10:00:00-03:00"),
      endsAt: new Date("2026-04-20T10:30:00-03:00"),
      notes: null,
    },
    {
      id: "apt_003",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      customerId: "pat_003",
      createdByUserId: "usr_admin_001",
      status: "missed",
      startsAt: new Date("2026-04-18T14:00:00-03:00"),
      endsAt: new Date("2026-04-18T14:30:00-03:00"),
      notes: "No-show",
    },
    {
      id: "apt_004",
      organizationId: "cln_dental_001",
      providerId: "pro_003",
      customerId: "pat_004",
      createdByUserId: "usr_admin_002",
      status: "attended",
      startsAt: new Date("2026-04-20T11:00:00-03:00"),
      endsAt: new Date("2026-04-20T11:40:00-03:00"),
      notes: "Limpeza",
    },
  ],
  auditEvents: [
    {
      id: "aud_001",
      organizationId: "cln_main_001",
      actorId: "usr_admin_001",
      action: "booking.created",
      targetType: "booking",
      targetId: "apt_001",
      occurredAt: new Date("2026-04-19T08:00:00-03:00"),
    },
    {
      id: "aud_002",
      organizationId: "cln_main_001",
      actorId: "usr_reception_001",
      action: "booking.confirmed",
      targetType: "booking",
      targetId: "apt_002",
      occurredAt: new Date("2026-04-19T09:15:00-03:00"),
    },
    {
      id: "aud_003",
      organizationId: "cln_dental_001",
      actorId: "usr_admin_002",
      action: "login.success",
      targetType: "user",
      targetId: "usr_admin_002",
      occurredAt: new Date("2026-04-19T07:40:00-03:00"),
    },
  ],
} as const;
