import { hashPassword } from "../../utils/password";

export const seedData = {
  organizations: [
    {
      id: "cln_main_001",
      legalName: "Organizationa Exemplo LTDA",
      tradeName: "Organizationa Exemplo",
      bookingPageSlug: "organizationa-exemplo",
      timezone: "America/Sao_Paulo",
      publicDescription: "Clínica multidisciplinar com agenda online para consultas, estética e terapias.",
      publicPhone: "+5511911111111",
      publicEmail: "contato@organization.test",
      addressLine: "Avenida Paulista",
      addressNumber: "1000",
      district: "Bela Vista",
      city: "São Paulo",
      state: "SP",
      postalCode: "01310-100",
      coverImageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1400&q=80",
      logoImageUrl: null,
      galleryImageUrls: ["https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=900&q=80"],
      isStorefrontPublished: true,
    },
    {
      id: "cln_derma_001",
      legalName: "Derma Prime Estética LTDA",
      tradeName: "Derma Prime Estética",
      bookingPageSlug: "derma-prime-estetica",
      timezone: "America/Sao_Paulo",
      publicDescription: "Estética facial e corporal com avaliação, limpeza de pele e procedimentos não invasivos.",
      publicPhone: "+5511955550101",
      publicEmail: "contato@dermaprime.test",
      addressLine: "Rua Oscar Freire",
      addressNumber: "780",
      district: "Jardins",
      city: "São Paulo",
      state: "SP",
      postalCode: "01426-001",
      coverImageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1400&q=80",
      logoImageUrl: null,
      galleryImageUrls: ["https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80"],
      isStorefrontPublished: true,
    },
    {
      id: "cln_therapy_001",
      legalName: "Mente Clara Terapias LTDA",
      tradeName: "Mente Clara Terapias",
      bookingPageSlug: "mente-clara-terapias",
      timezone: "America/Sao_Paulo",
      publicDescription: "Psicologia e terapias com agenda reservada, atendimento humanizado e lembretes automáticos.",
      publicPhone: "+5511955550202",
      publicEmail: "contato@menteclara.test",
      addressLine: "Rua Vergueiro",
      addressNumber: "1500",
      district: "Vila Mariana",
      city: "São Paulo",
      state: "SP",
      postalCode: "04101-000",
      coverImageUrl: "https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&w=1400&q=80",
      logoImageUrl: null,
      galleryImageUrls: ["https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&w=900&q=80"],
      isStorefrontPublished: true,
    },
    {
      id: "cln_barber_001",
      legalName: "Barbearia Norte LTDA",
      tradeName: "Barbearia Norte",
      bookingPageSlug: "barbearia-norte",
      timezone: "America/Sao_Paulo",
      publicDescription: "Corte, barba e cuidados masculinos com horários rápidos para agendamento online.",
      publicPhone: "+5511955550303",
      publicEmail: "contato@barbearianorte.test",
      addressLine: "Avenida Braz Leme",
      addressNumber: "900",
      district: "Santana",
      city: "São Paulo",
      state: "SP",
      postalCode: "02022-001",
      coverImageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1400&q=80",
      logoImageUrl: null,
      galleryImageUrls: ["https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80"],
      isStorefrontPublished: true,
    },
    {
      id: "cln_dental_001",
      legalName: "Odonto Centro LTDA",
      tradeName: "Odonto Centro",
      bookingPageSlug: "odonto-centro",
      timezone: "America/Sao_Paulo",
      publicDescription: "Atendimento odontológico com horários para avaliação, limpeza e acompanhamento.",
      publicPhone: "+5511944444444",
      publicEmail: "contato@odonto.test",
      addressLine: "Rua das Flores",
      addressNumber: "250",
      district: "Centro",
      city: "São Paulo",
      state: "SP",
      postalCode: "01010-000",
      coverImageUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1400&q=80",
      logoImageUrl: null,
      galleryImageUrls: ["https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=900&q=80"],
      isStorefrontPublished: true,
    },
  ],
  billingPlans: [
    {
      id: "plan_free_test",
      code: "free",
      name: "Gratuito",
      description: "Plano gratuito Hubly para organizações existentes",
      amountCents: 0,
      currency: "brl",
      interval: "month",
      stripeMode: "test",
      stripeProductId: null,
      stripePriceId: null,
      isActive: true,
      isDefault: true,
    },
    {
      id: "plan_pro_test",
      code: "pro",
      name: "Pro",
      description: "Plano Pro Hubly",
      amountCents: 6990,
      currency: "brl",
      interval: "month",
      stripeMode: "test",
      stripeProductId: null,
      stripePriceId: null,
      isActive: true,
      isDefault: false,
    },
    {
      id: "plan_premium_test",
      code: "premium",
      name: "Premium",
      description: "Plano Premium Hubly",
      amountCents: 12990,
      currency: "brl",
      interval: "month",
      stripeMode: "test",
      stripeProductId: null,
      stripePriceId: null,
      isActive: true,
      isDefault: false,
    },
    {
      id: "plan_free_live",
      code: "free",
      name: "Gratuito",
      description: "Plano gratuito Hubly para organizações existentes",
      amountCents: 0,
      currency: "brl",
      interval: "month",
      stripeMode: "live",
      stripeProductId: null,
      stripePriceId: null,
      isActive: true,
      isDefault: true,
    },
    {
      id: "plan_pro_live",
      code: "pro",
      name: "Pro",
      description: "Plano Pro Hubly",
      amountCents: 6990,
      currency: "brl",
      interval: "month",
      stripeMode: "live",
      stripeProductId: null,
      stripePriceId: null,
      isActive: true,
      isDefault: false,
    },
    {
      id: "plan_premium_live",
      code: "premium",
      name: "Premium",
      description: "Plano Premium Hubly",
      amountCents: 12990,
      currency: "brl",
      interval: "month",
      stripeMode: "live",
      stripeProductId: null,
      stripePriceId: null,
      isActive: true,
      isDefault: false,
    },
  ],
  organizationSubscriptions: [
    {
      id: "sub_cln_main_001_test",
      organizationId: "cln_main_001",
      billingPlanId: "plan_free_test",
      status: "active",
      stripeMode: "test",
      stripeCustomerId: null,
      stripeSubscriptionId: null,
      stripeCheckoutSessionId: null,
      stripePriceId: null,
      trialEndsAt: null,
      currentPeriodStart: null,
      currentPeriodEnd: null,
      cancelAtPeriodEnd: false,
    },
    {
      id: "sub_cln_dental_001_test",
      organizationId: "cln_dental_001",
      billingPlanId: "plan_free_test",
      status: "active",
      stripeMode: "test",
      stripeCustomerId: null,
      stripeSubscriptionId: null,
      stripeCheckoutSessionId: null,
      stripePriceId: null,
      trialEndsAt: null,
      currentPeriodStart: null,
      currentPeriodEnd: null,
      cancelAtPeriodEnd: false,
    },
    {
      id: "sub_cln_derma_001_test",
      organizationId: "cln_derma_001",
      billingPlanId: "plan_free_test",
      status: "active",
      stripeMode: "test",
      stripeCustomerId: null,
      stripeSubscriptionId: null,
      stripeCheckoutSessionId: null,
      stripePriceId: null,
      trialEndsAt: null,
      currentPeriodStart: null,
      currentPeriodEnd: null,
      cancelAtPeriodEnd: false,
    },
    {
      id: "sub_cln_therapy_001_test",
      organizationId: "cln_therapy_001",
      billingPlanId: "plan_free_test",
      status: "active",
      stripeMode: "test",
      stripeCustomerId: null,
      stripeSubscriptionId: null,
      stripeCheckoutSessionId: null,
      stripePriceId: null,
      trialEndsAt: null,
      currentPeriodStart: null,
      currentPeriodEnd: null,
      cancelAtPeriodEnd: false,
    },
    {
      id: "sub_cln_barber_001_test",
      organizationId: "cln_barber_001",
      billingPlanId: "plan_free_test",
      status: "active",
      stripeMode: "test",
      stripeCustomerId: null,
      stripeSubscriptionId: null,
      stripeCheckoutSessionId: null,
      stripePriceId: null,
      trialEndsAt: null,
      currentPeriodStart: null,
      currentPeriodEnd: null,
      cancelAtPeriodEnd: false,
    },
  ],
  users: [
    {
      id: "usr_admin_001",
      organizationId: "cln_main_001",
      fullName: "Ana Martins",
      email: "admin@organization.test",
      phone: "+5511911111111",
      role: "administrator",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_reception_001",
      organizationId: "cln_main_001",
      fullName: "Bruna Lopes",
      email: "recepcao@organization.test",
      phone: "+5511922222222",
      role: "reception",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_pro_001",
      organizationId: "cln_main_001",
      fullName: "Dr. Ricardo Alves",
      email: "ricardo@organization.test",
      phone: "+5511933333333",
      role: "provider",
      providerId: "pro_002",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_admin_002",
      organizationId: "cln_dental_001",
      fullName: "Mariana Costa",
      email: "admin@odonto.test",
      phone: "+5511944444444",
      role: "administrator",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_admin_003",
      organizationId: "cln_derma_001",
      fullName: "Camila Rocha",
      email: "admin@dermaprime.test",
      phone: "+5511955550101",
      role: "administrator",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_admin_004",
      organizationId: "cln_therapy_001",
      fullName: "Sofia Almeida",
      email: "admin@menteclara.test",
      phone: "+5511955550202",
      role: "administrator",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
    {
      id: "usr_admin_005",
      organizationId: "cln_barber_001",
      fullName: "Marcos Nogueira",
      email: "admin@barbearianorte.test",
      phone: "+5511955550303",
      role: "administrator",
      passwordHash: hashPassword("password123"),
      isActive: true,
    },
  ],
  providers: [
    {
      id: "pro_001",
      organizationId: "cln_main_001",
      fullName: "Dra. Ana Souza",
      specialty: "Organizationa Geral",
      isActive: true,
    },
    {
      id: "pro_002",
      organizationId: "cln_main_001",
      fullName: "Dr. Ricardo Alves",
      specialty: "Cardiologia",
      isActive: true,
    },
    {
      id: "pro_004",
      organizationId: "cln_derma_001",
      fullName: "Dra. Camila Rocha",
      specialty: "Estética facial",
      isActive: true,
    },
    {
      id: "pro_005",
      organizationId: "cln_derma_001",
      fullName: "Paula Mendes",
      specialty: "Limpeza de pele",
      isActive: true,
    },
    {
      id: "pro_006",
      organizationId: "cln_therapy_001",
      fullName: "Dra. Sofia Almeida",
      specialty: "Psicologia",
      isActive: true,
    },
    {
      id: "pro_007",
      organizationId: "cln_barber_001",
      fullName: "Marcos Nogueira",
      specialty: "Barbearia",
      isActive: true,
    },
    {
      id: "pro_003",
      organizationId: "cln_dental_001",
      fullName: "Dra. Paula Nunes",
      specialty: "Odontologia",
      isActive: true,
    },
  ],
  providerAvailabilities: [
    {
      id: "avl_001",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      weekday: 1,
      workStart: "08:00",
      workEnd: "18:00",
      lunchStart: "12:30",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_002",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      weekday: 2,
      workStart: "08:00",
      workEnd: "18:00",
      lunchStart: "12:30",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_003",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      weekday: 3,
      workStart: "08:00",
      workEnd: "18:00",
      lunchStart: "12:30",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_004",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      weekday: 1,
      workStart: "09:00",
      workEnd: "17:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_004_2",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      weekday: 2,
      workStart: "09:00",
      workEnd: "17:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_004_3",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      weekday: 3,
      workStart: "09:00",
      workEnd: "17:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_004_4",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      weekday: 4,
      workStart: "09:00",
      workEnd: "17:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_004_5",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      weekday: 5,
      workStart: "09:00",
      workEnd: "17:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_006",
      organizationId: "cln_dental_001",
      providerId: "pro_003",
      weekday: 2,
      workStart: "08:00",
      workEnd: "16:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_007",
      organizationId: "cln_derma_001",
      providerId: "pro_004",
      weekday: 1,
      workStart: "10:00",
      workEnd: "19:00",
      lunchStart: "14:00",
      lunchEnd: "15:00",
      isActive: true,
    },
    {
      id: "avl_008",
      organizationId: "cln_derma_001",
      providerId: "pro_005",
      weekday: 2,
      workStart: "09:00",
      workEnd: "18:00",
      lunchStart: "13:00",
      lunchEnd: "14:00",
      isActive: true,
    },
    {
      id: "avl_009",
      organizationId: "cln_therapy_001",
      providerId: "pro_006",
      weekday: 1,
      workStart: "08:00",
      workEnd: "17:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
    {
      id: "avl_010",
      organizationId: "cln_barber_001",
      providerId: "pro_007",
      weekday: 1,
      workStart: "09:00",
      workEnd: "20:00",
      lunchStart: "13:00",
      lunchEnd: "14:00",
      isActive: true,
    },
    {
      id: "avl_005",
      organizationId: "cln_dental_001",
      providerId: "pro_003",
      weekday: 1,
      workStart: "08:00",
      workEnd: "16:00",
      lunchStart: "12:00",
      lunchEnd: "13:00",
      isActive: true,
    },
  ],
  serviceOfferings: [
    {
      id: "svc_001",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      name: "Consulta inicial",
      durationMinutes: 30,
      priceCents: 18000,
      isActive: true,
    },
    {
      id: "svc_002",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      name: "Consulta cardiologia",
      durationMinutes: 40,
      priceCents: 26000,
      isActive: true,
    },
    {
      id: "svc_003",
      organizationId: "cln_dental_001",
      providerId: "pro_003",
      name: "Avaliação odontológica",
      durationMinutes: 40,
      priceCents: 12000,
      isActive: true,
    },
    {
      id: "svc_004",
      organizationId: "cln_derma_001",
      providerId: "pro_004",
      name: "Avaliação estética",
      durationMinutes: 30,
      priceCents: 9000,
      isActive: true,
    },
    {
      id: "svc_005",
      organizationId: "cln_derma_001",
      providerId: "pro_005",
      name: "Limpeza de pele",
      durationMinutes: 60,
      priceCents: 22000,
      isActive: true,
    },
    {
      id: "svc_006",
      organizationId: "cln_therapy_001",
      providerId: "pro_006",
      name: "Sessão de terapia",
      durationMinutes: 50,
      priceCents: 18000,
      isActive: true,
    },
    {
      id: "svc_007",
      organizationId: "cln_barber_001",
      providerId: "pro_007",
      name: "Corte e barba",
      durationMinutes: 45,
      priceCents: 9000,
      isActive: true,
    },
  ],
  customers: [
    {
      id: "pat_001",
      organizationId: "cln_main_001",
      fullName: "Carlos Pereira",
      email: "carlos@customer.test",
      phone: "+5511999999999",
    },
    {
      id: "pat_002",
      organizationId: "cln_main_001",
      fullName: "Fernanda Lima",
      email: "fernanda@customer.test",
      phone: "+5511988888888",
    },
    {
      id: "pat_003",
      organizationId: "cln_main_001",
      fullName: "Julio Rocha",
      email: null,
      phone: "+5511977777777",
    },
    {
      id: "pat_004",
      organizationId: "cln_dental_001",
      fullName: "Patricia Gomes",
      email: "patricia@customer.test",
      phone: "+5511966666666",
    },
  ],
  bookings: [
    {
      id: "apt_001",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      customerId: "pat_001",
      createdByUserId: "usr_reception_001",
      status: "scheduled",
      startsAt: new Date("2026-04-20T09:00:00-03:00"),
      endsAt: new Date("2026-04-20T09:30:00-03:00"),
      notes: "Retorno",
    },
    {
      id: "apt_002",
      organizationId: "cln_main_001",
      providerId: "pro_002",
      customerId: "pat_002",
      createdByUserId: "usr_reception_001",
      status: "confirmed",
      startsAt: new Date("2026-04-20T10:00:00-03:00"),
      endsAt: new Date("2026-04-20T10:30:00-03:00"),
      notes: null,
    },
    {
      id: "apt_003",
      organizationId: "cln_main_001",
      providerId: "pro_001",
      customerId: "pat_003",
      createdByUserId: "usr_admin_001",
      status: "missed",
      startsAt: new Date("2026-04-18T14:00:00-03:00"),
      endsAt: new Date("2026-04-18T14:30:00-03:00"),
      notes: "No-show",
    },
    {
      id: "apt_004",
      organizationId: "cln_dental_001",
      providerId: "pro_003",
      customerId: "pat_004",
      createdByUserId: "usr_admin_002",
      status: "attended",
      startsAt: new Date("2026-04-20T11:00:00-03:00"),
      endsAt: new Date("2026-04-20T11:40:00-03:00"),
      notes: "Limpeza",
    },
  ],
  auditEvents: [
    {
      id: "aud_001",
      organizationId: "cln_main_001",
      actorId: "usr_admin_001",
      action: "booking.created",
      targetType: "booking",
      targetId: "apt_001",
      occurredAt: new Date("2026-04-19T08:00:00-03:00"),
    },
    {
      id: "aud_002",
      organizationId: "cln_main_001",
      actorId: "usr_reception_001",
      action: "booking.confirmed",
      targetType: "booking",
      targetId: "apt_002",
      occurredAt: new Date("2026-04-19T09:15:00-03:00"),
    },
    {
      id: "aud_003",
      organizationId: "cln_dental_001",
      actorId: "usr_admin_002",
      action: "login.success",
      targetType: "user",
      targetId: "usr_admin_002",
      occurredAt: new Date("2026-04-19T07:40:00-03:00"),
    },
  ],
} as const;
